#include "st_address_sanitizer.h"

#include <stdio.h>

#include "../frontend/st_lexer.h"
#include "../frontend/st_parser.h"
#include "../utils/st_string.h"

static b8 ST_asan_expr_is_call_to(ST_expr_t *e, const char *name) {
    return e && e->kind == ST_EX_CALL && e->call.callee &&
           e->call.callee->kind == ST_EX_IDENT && ST_string_eq_cstr(e->call.callee->name, name);
}

static void ST_asan_walk_expr(ST_arena_t *arena, ST_expr_t *e, ST_string_t file);

static void ST_asan_rewrite_if_matched(ST_arena_t *arena, ST_expr_t *e, ST_string_t file) {
    const char *new_name = NULL;
    if (ST_asan_expr_is_call_to(e, "heap_alloc"))
        new_name = "__asan_alloc";
    else if (ST_asan_expr_is_call_to(e, "heap_free"))
        new_name = "__asan_free";
    if (!new_name)
        return;

    e->call.callee->name = ST_cstr_to_str((char *)new_name);

    ST_expr_t *file_e = ST_expr_new(arena, ST_EX_STR, e->line, e->col);
    file_e->sval = file;
    ST_expr_t *line_e = ST_expr_new(arena, ST_EX_INT, e->line, e->col);
    line_e->ival = (i64)e->line;
    ST_expr_t *col_e = ST_expr_new(arena, ST_EX_INT, e->line, e->col);
    col_e->ival = (i64)e->col;

    ST_arg_t file_arg = {.name = {0}, .value = file_e};
    ST_arg_t line_arg = {.name = {0}, .value = line_e};
    ST_arg_t col_arg = {.name = {0}, .value = col_e};
    ST_da_append_arena(arena, &e->call.args, file_arg);
    ST_da_append_arena(arena, &e->call.args, line_arg);
    ST_da_append_arena(arena, &e->call.args, col_arg);
}

static void ST_asan_walk_expr(ST_arena_t *arena, ST_expr_t *e, ST_string_t file) {
    if (!e)
        return;

    switch (e->kind) {
        case ST_EX_UNARY:
            ST_asan_walk_expr(arena, e->unary.operand, file);
            break;
        case ST_EX_BINARY:
            ST_asan_walk_expr(arena, e->bin.l, file);
            ST_asan_walk_expr(arena, e->bin.r, file);
            break;
        case ST_EX_CALL:
            ST_asan_walk_expr(arena, e->call.callee, file);
            ST_forrange(0, e->call.args.count) ST_asan_walk_expr(arena, e->call.args.items[i].value, file);
            break;
        case ST_EX_FIELD:
            ST_asan_walk_expr(arena, e->field.base, file);
            break;
        case ST_EX_INDEX:
            ST_asan_walk_expr(arena, e->index.base, file);
            ST_asan_walk_expr(arena, e->index.index, file);
            break;
        case ST_EX_CAST:
            ST_asan_walk_expr(arena, e->cast.operand, file);
            break;
        case ST_EX_STRUCT_LIT:
            ST_forrange(0, e->struct_lit.inits.count)
                ST_asan_walk_expr(arena, e->struct_lit.inits.items[i].value, file);
            break;
        case ST_EX_SIZEOF:
        case ST_EX_TYPEOF:
        case ST_EX_TYPEINFO:
        case ST_EX_KIND:
        case ST_EX_CSTR:
        case ST_EX_FIELDS:
            ST_asan_walk_expr(arena, e->tyop.operand, file);
            break;
        case ST_EX_COMP_ERROR:
            ST_forrange(0, e->comp_error.args.count) ST_asan_walk_expr(arena, e->comp_error.args.items[i], file);
            break;
        case ST_EX_STR_FROM_RAW:
            ST_asan_walk_expr(arena, e->str_from_raw.ptr, file);
            ST_asan_walk_expr(arena, e->str_from_raw.len, file);
            break;
        case ST_EX_INT:
        case ST_EX_FLOAT:
        case ST_EX_STR:
        case ST_EX_CHAR:
        case ST_EX_BOOL:
        case ST_EX_NULL:
        case ST_EX_IDENT:
        case ST_EX_ARRAY_NEW:
        case ST_EX_ASM:
        case ST_EX_PACK_FOLD:
        case ST_EX_COUNT:
            break;
    }

    ST_asan_rewrite_if_matched(arena, e, file);
}

static void ST_asan_walk_stmts(ST_arena_t *arena, ST_stmts_t *stmts, ST_string_t file);

static void ST_asan_walk_stmt(ST_arena_t *arena, ST_stmt_t *s, ST_string_t file) {
    if (!s)
        return;

    switch (s->kind) {
        case ST_ST_EXPR:
            ST_asan_walk_expr(arena, s->expr, file);
            break;
        case ST_ST_DECL:
            ST_asan_walk_expr(arena, s->decl.init, file);
            break;
        case ST_ST_ASSIGN:
            ST_asan_walk_expr(arena, s->assign.lhs, file);
            ST_asan_walk_expr(arena, s->assign.rhs, file);
            break;
        case ST_ST_MULTI_BIND:
            ST_forrange(0, s->multi.values.count) ST_asan_walk_expr(arena, s->multi.values.items[i], file);
            break;
        case ST_ST_IF:
            ST_asan_walk_expr(arena, s->if_.cond, file);
            ST_asan_walk_stmts(arena, &s->if_.then_body, file);
            ST_asan_walk_stmt(arena, s->if_.else_stmt, file);
            break;
        case ST_ST_SWITCH:
            ST_asan_walk_expr(arena, s->switch_.cond, file);
            ST_forrange(0, s->switch_.cases.count) {
                ST_case_t *c = &s->switch_.cases.items[i];
                ST_forrange(0, c->values.count) ST_asan_walk_expr(arena, c->values.items[i], file);
                ST_asan_walk_stmts(arena, &c->body, file);
            }
            break;
        case ST_ST_WHILE:
            ST_asan_walk_expr(arena, s->while_.cond, file);
            ST_asan_walk_stmts(arena, &s->while_.body, file);
            break;
        case ST_ST_FOR_RANGE:
            ST_asan_walk_expr(arena, s->for_range.lo, file);
            ST_asan_walk_expr(arena, s->for_range.hi, file);
            ST_asan_walk_stmts(arena, &s->for_range.body, file);
            break;
        case ST_ST_FOR_ARRAY:
            ST_asan_walk_expr(arena, s->for_array.target, file);
            ST_asan_walk_stmts(arena, &s->for_array.body, file);
            break;
        case ST_ST_RETURN:
            ST_forrange(0, s->ret.values.count) ST_asan_walk_expr(arena, s->ret.values.items[i], file);
            break;
        case ST_ST_BLOCK:
            ST_asan_walk_stmts(arena, &s->block, file);
            break;
        case ST_ST_DEFER:
            ST_asan_walk_stmt(arena, s->defer_stmt, file);
            break;
        case ST_ST_BREAK:
        case ST_ST_CONTINUE:
        case ST_ST_LABEL:
        case ST_ST_GODOWN:
        case ST_ST_ASM:
        case ST_ST_PACK_EXPAND:
        case ST_ST_COUNT:
            break;
    }
}

static void ST_asan_walk_stmts(ST_arena_t *arena, ST_stmts_t *stmts, ST_string_t file) {
    ST_forrange(0, stmts->count) ST_asan_walk_stmt(arena, stmts->items[i], file);
}

static ST_expr_t *ST_asan_report_leaks_call(ST_arena_t *arena, u32 line, u32 col) {
    ST_expr_t *callee = ST_expr_new(arena, ST_EX_IDENT, line, col);
    callee->name = ST_cstr_to_str((char *)"__asan_report_leaks");

    ST_expr_t *call = ST_expr_new(arena, ST_EX_CALL, line, col);
    call->call.callee = callee;
    return call;
}

static const char *ST_asan_extern_decls_src =
    "extern fn __asan_alloc(size: i64, file: string, line: i64, col: i64) -> (*void, i64);\n"
    "extern fn __asan_free(ptr: *void, file: string, line: i64, col: i64) -> void;\n"
    "extern fn __asan_init() -> void;\n"
    "extern fn __asan_report_leaks() -> void;\n"
    "\n"    ;

static const char *ST_asan_runtime_asm_src =
    "\n"
    "section .bss\n"
    "align 8\n"
    "__asan_records:      resb 65536 * 104\n"
    "\n"
    "__asan_record_count: resq 1\n"
    "__asan_initialized:  resb 1\n"
    "__asan_sigact_buf:   resb 32\n"
    "__asan_hexbuf:       resb 18\n"
    "__asan_decbuf:       resb 20\n"
    "\n"
    "section .rodata\n"
    "__asan_msg_colon: db \":\"\n"
    "__asan_msg_colon_space: db \": \"\n"
    "__asan_msg_err: db \"error: \"\n"
    "__asan_msg_err_len equ $ - __asan_msg_err\n"
    "__asan_msg_note: db \"note: \"\n"
    "__asan_msg_note_len equ $ - __asan_msg_note\n"
    "__asan_msg_overflow: db \"ASAN: heap-buffer-overflow, faulting address \"\n"
    "__asan_msg_overflow_len equ $ - __asan_msg_overflow\n"
    "__asan_msg_uaf_segv: db \"ASAN: use-after-free, faulting address \"\n"
    "__asan_msg_uaf_segv_len equ $ - __asan_msg_uaf_segv\n"
    "__asan_msg_allocated_here: db \"allocated here\"\n"
    "__asan_msg_allocated_here_len equ $ - __asan_msg_allocated_here\n"
    "__asan_msg_freed_here: db \"freed here\"\n"
    "__asan_msg_freed_here_len equ $ - __asan_msg_freed_here\n"
    "__asan_msg_leak: db \"ASAN: memory leak, \"\n"
    "__asan_msg_leak_len equ $ - __asan_msg_leak\n"
    "__asan_msg_bytes_never: db \" bytes never freed\"\n"
    "__asan_msg_bytes_never_len equ $ - __asan_msg_bytes_never\n"
    "__asan_msg_double_free2: db \"ASAN: double free\"\n"
    "__asan_msg_double_free2_len equ $ - __asan_msg_double_free2\n"
    "__asan_msg_orig_alloc: db \"originally allocated here\"\n"
    "__asan_msg_orig_alloc_len equ $ - __asan_msg_orig_alloc\n"
    "__asan_msg_prev_freed: db \"previously freed here\"\n"
    "__asan_msg_prev_freed_len equ $ - __asan_msg_prev_freed\n"
    "__asan_msg_invalid_free2: db \"ASAN: invalid free -- pointer was never returned by heap_alloc\"\n"
    "__asan_msg_invalid_free2_len equ $ - __asan_msg_invalid_free2\n"
    "\n"
    "__asan_msg_sep:         db \"==================================================\", 10\n"
    "__asan_msg_sep_len equ $ - __asan_msg_sep\n"
    "__asan_msg_segv:        db \"ASAN: SEGV\", 10\n"
    "__asan_msg_segv_len equ $ - __asan_msg_segv\n"
    "__asan_msg_faddr:       db \"    faulting address: \"\n"
    "__asan_msg_faddr_len equ $ - __asan_msg_faddr\n"
    "__asan_msg_belongs:     db \"    belongs to a \"\n"
    "__asan_msg_belongs_len equ $ - __asan_msg_belongs\n"
    "__asan_msg_bytes_alloc: db \"-byte heap allocation, allocated at line \"\n"
    "__asan_msg_bytes_alloc_len equ $ - __asan_msg_bytes_alloc\n"
    "__asan_msg_col:         db \", col \"\n"
    "__asan_msg_col_len equ $ - __asan_msg_col\n"
    "__asan_msg_nl:          db 10\n"
    "__asan_msg_uaf:         db \"    this allocation was already freed (use-after-free)\", 10\n"
    "__asan_msg_uaf_len equ $ - __asan_msg_uaf\n"
    "__asan_msg_nullderef:   db \"    null (or near-null) pointer dereference\", 10\n"
    "__asan_msg_nullderef_len equ $ - __asan_msg_nullderef\n"
    "__asan_msg_untracked:   db \"    address does not belong to any tracked allocation\", 10\n"
    "__asan_msg_untracked_len equ $ - __asan_msg_untracked\n"
    "__asan_msg_trace:       db \"    stack trace (frame pointers):\", 10\n"
    "__asan_msg_trace_len equ $ - __asan_msg_trace\n"
    "__asan_msg_frame:       db \"      #\"\n"
    "__asan_msg_frame_len equ $ - __asan_msg_frame\n"
    "__asan_msg_in:          db \"in \"\n"
    "__asan_msg_in_len equ $ - __asan_msg_in\n"
    "__asan_msg_frame_hash: db \" frame #\"\n"
    "__st_msg_oob:          db \"index out of bounds: index \"\n"
    "__st_msg_oob_len equ $ - __st_msg_oob\n"
    "__st_msg_oob_of:       db \", length \"\n"
    "__st_msg_oob_of_len equ $ - __st_msg_oob_of\n"
    "__asan_msg_frame_hash_len equ $ - __asan_msg_frame_hash\n"
    "__asan_msg_retaddr:     db \" return address \"\n"
    "__asan_msg_retaddr_len equ $ - __asan_msg_retaddr\n"
    "__asan_msg_invalid_free: db \"ASAN: invalid free -- pointer was never returned by heap_alloc\", 10\n"
    "__asan_msg_invalid_free_len equ $ - __asan_msg_invalid_free\n"
    "__asan_msg_at_line:     db \"    at line \"\n"
    "__asan_msg_at_line_len equ $ - __asan_msg_at_line\n"
    "__asan_msg_double_free: db \"ASAN: double free\", 10, \"    originally allocated at line \"\n"
    "__asan_msg_double_free_len equ $ - __asan_msg_double_free\n"
    "__asan_msg_this_free:   db \"    this free is at line \"\n"
    "__asan_msg_this_free_len equ $ - __asan_msg_this_free\n"
    "__asan_msg_leak_header: db \"ASAN: memory leak(s) detected\", 10\n"
    "__asan_msg_leak_header_len equ $ - __asan_msg_leak_header\n"
    "__asan_msg_leaked:      db \"    leaked \"\n"
    "__asan_msg_leaked_len equ $ - __asan_msg_leaked\n"
    "__asan_msg_bytes_line:  db \" bytes, allocated at line \"\n"
    "__asan_msg_bytes_line_len equ $ - __asan_msg_bytes_line\n"
    "\n"
    "section .text\n"
    "\n"
    "__asan_raw_mmap:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rdx, rsi\n"
    "    mov rsi, rdi\n"
    "    xor rdi, rdi\n"
    "    mov r10, 34\n"
    "    mov r8, -1\n"
    "    xor r9, r9\n"
    "    mov rax, 9\n"
    "    syscall\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_raw_mprotect:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, 10\n"
    "    syscall\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_raw_write:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, 1\n"
    "    syscall\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_raw_exit:\n"
    "    mov rax, 60\n"
    "    syscall\n"
    "\n"
    "__asan_write_lit:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rdx, rsi\n"
    "    mov rsi, rdi\n"
    "    mov rdi, 2\n"
    "    call __asan_raw_write\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_write_hex:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, rdi\n"
    "    lea r9, [rel __asan_hexbuf]\n"
    "    mov byte [r9], 0x30\n"
    "    mov byte [r9+1], 0x78\n"
    "    mov r10, 15\n"
    ".loop:\n"
    "    mov rdx, rax\n"
    "    mov rcx, r10\n"
    "    shl rcx, 2\n"
    "    shr rdx, cl\n"
    "    and rdx, 15\n"
    "    cmp rdx, 10\n"
    "    jl .digit\n"
    "    add rdx, 87\n"
    "    jmp .store\n"
    ".digit:\n"
    "    add rdx, 48\n"
    ".store:\n"
    "    mov r8, 15\n"
    "    sub r8, r10\n"
    "\n"
    "    mov [r9 + 2 + r8], dl\n"
    "    dec r10\n"
    "    jns .loop\n"
    "    mov rdi, 2\n"
    "    lea rsi, [rel __asan_hexbuf]\n"
    "    mov rdx, 18\n"
    "    call __asan_raw_write\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_write_dec:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, rdi\n"
    "    lea r9, [rel __asan_decbuf]\n"
    "    mov r10, 20\n"
    "    test rax, rax\n"
    "    jnz .conv\n"
    "    dec r10\n"
    "    mov byte [r9 + r10], 0x30\n"
    "    jmp .out\n"
    ".conv:\n"
    ".loop:\n"
    "    xor rdx, rdx\n"
    "    mov r8, 10\n"
    "    div r8\n"
    "    add rdx, 48\n"
    "    dec r10\n"
    "    mov [r9 + r10], dl\n"
    "    test rax, rax\n"
    "    jnz .loop\n"
    ".out:\n"
    "    mov rdi, 2\n"
    "    lea rsi, [rel __asan_decbuf]\n"
    "    add rsi, r10\n"
    "    mov rdx, 20\n"
    "    sub rdx, r10\n"
    "    call __asan_raw_write\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_write_loc:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 32\n"
    "    mov [rbp-8], rdi\n"
    "    mov [rbp-16], rsi\n"
    "    mov [rbp-24], rdx\n"
    "    mov [rbp-32], rcx\n"
    "    mov rdi, [rbp-8]\n"
    "    mov rsi, [rbp-16]\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_colon]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-24]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [rel __asan_msg_colon]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-32]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [rel __asan_msg_colon_space]\n"
    "    mov rsi, 2\n"
    "    call __asan_write_lit\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__st_bounds_fail:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 16\n"
    "    mov [rbp-8], rdi\n"
    "    mov [rbp-16], rsi\n"
    "    mov rdi, rdx\n"
    "    mov rsi, rcx\n"
    "    mov rdx, r8\n"
    "    mov rcx, r9\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __st_msg_oob]\n"
    "    mov rsi, __st_msg_oob_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-8]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [rel __st_msg_oob_of]\n"
    "    mov rsi, __st_msg_oob_of_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-16]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, 1\n"
    "    call __asan_raw_exit\n"
    "\n"
    "st_string_eq:\n"
    "    mov r8, [rdi]\n"
    "    mov r9d, [rdi+8]\n"
    "    mov r10, [rsi]\n"
    "    mov r11d, [rsi+8]\n"
    "    cmp r9d, r11d\n"
    "    jne .st_string_eq_false\n"
    "    xor rcx, rcx\n"
    ".st_string_eq_loop:\n"
    "    cmp ecx, r9d\n"
    "    jge .st_string_eq_true\n"
    "    movzx eax, byte [r8+rcx]\n"
    "    movzx edx, byte [r10+rcx]\n"
    "    cmp al, dl\n"
    "    jne .st_string_eq_false\n"
    "    inc rcx\n"
    "    jmp .st_string_eq_loop\n"
    ".st_string_eq_true:\n"
    "    mov rax, 1\n"
    "    ret\n"
    ".st_string_eq_false:\n"
    "    xor rax, rax\n"
    "    ret\n"
    "\n"
    "__asan_find_record:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov r9, rdi\n"
    "    xor rcx, rcx\n"
    "    mov rdx, [rel __asan_record_count]\n"
    ".loop:\n"
    "    cmp rcx, rdx\n"
    "    jge .notfound\n"
    "    mov rax, rcx\n"
    "    imul rax, 104\n"
    "    lea r8, [rel __asan_records]\n"
    "    add r8, rax\n"
    "    mov r10, [r8]\n"
    "    sub r10, 4096\n"
    "    cmp r9, r10\n"
    "    jl .next\n"
    "    mov r10, [r8]\n"
    "    add r10, [r8+8]\n"
    "    add r10, 4096\n"
    "    cmp r9, r10\n"
    "    jge .next\n"
    "    mov rax, rcx\n"
    "    leave\n"
    "    ret\n"
    ".next:\n"
    "    inc rcx\n"
    "    jmp .loop\n"
    ".notfound:\n"
    "    mov rax, -1\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_find_record_by_ptr:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov r9, rdi\n"
    "    xor rcx, rcx\n"
    "    mov rdx, [rel __asan_record_count]\n"
    ".loop:\n"
    "    cmp rcx, rdx\n"
    "    jge .notfound\n"
    "    mov rax, rcx\n"
    "    imul rax, 104\n"
    "    lea r8, [rel __asan_records]\n"
    "    add r8, rax\n"
    "    cmp [r8], r9\n"
    "    je .found\n"
    "    inc rcx\n"
    "    jmp .loop\n"
    ".found:\n"
    "    mov rax, rcx\n"
    "    leave\n"
    "    ret\n"
    ".notfound:\n"
    "    mov rax, -1\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_lookup_line:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 16\n"
    "    mov qword [rbp-8], 0\n"
    "    mov r9, rdi\n"
    "    mov r10, [rel __asan_dbg_row_count]\n"
    "    lea r11, [rel __asan_dbg_rows]\n"
    "    xor rcx, rcx\n"
    ".loop:\n"
    "    cmp rcx, r10\n"
    "    jge .done\n"
    "    mov rax, rcx\n"
    "    imul rax, 48\n"
    "    add rax, r11\n"
    "    cmp qword [rax], r9\n"
    "    jg .done\n"
    "\n"
    "    mov [rbp-8], rax\n"
    "    inc rcx\n"
    "    jmp .loop\n"
    ".done:\n"
    "    mov rax, [rbp-8]\n"
    "    test rax, rax\n"
    "    jz .notfound\n"
    "    mov r10, [rax+40]\n"
    "    mov rdx, r10\n"
    "    imul rdx, 24\n"
    "    lea rcx, [rel __asan_dbg_fn_names]\n"
    "    add rdx, rcx\n"
    "    cmp r9, [rdx+16]\n"
    "    jge .notfound\n"
    "\n"
    "    mov rdx, [rax+8]\n"
    "    mov rcx, [rax+16]\n"
    "    mov r8, [rax+24]\n"
    "    mov r9, [rax+32]\n"
    "    mov rax, 1\n"
    "    leave\n"
    "    ret\n"
    ".notfound:\n"
    "    xor rax, rax\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_fn_name:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, rdi\n"
    "    imul rax, 24\n"
    "    lea r10, [rel __asan_dbg_fn_names]\n"
    "    add rax, r10\n"
    "    mov rdx, [rax]\n"
    "    mov rcx, [rax+8]\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_print_trace:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 32\n"
    "    push rbx\n"
    "    push r12\n"
    "    mov rbx, rdi\n"
    "\n"
    "    lea rax, [rel __asan_msg_trace]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_trace_len\n"
    "    call __asan_write_lit\n"
    "    xor r12, r12\n"
    ".loop:\n"
    "    cmp r12, 32\n"
    "    jge .done\n"
    "    test rbx, rbx\n"
    "    jz .done\n"
    "    mov rax, [rbx+8]\n"
    "    test rax, rax\n"
    "    jz .done\n"
    "    mov [rbp-8], rax\n"
    "    mov rdi, rax\n"
    "    call __asan_lookup_line\n"
    "    test rax, rax\n"
    "    jz .frame_no_loc\n"
    "    mov [rbp-16], r10\n"
    "    mov rdi, rdx\n"
    "    mov rsi, rcx\n"
    "    mov rdx, r8\n"
    "    mov rcx, r9\n"
    "    call __asan_write_loc\n"
    "    lea rax, [rel __asan_msg_in]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_in_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-16]\n"
    "    call __asan_fn_name\n"
    "    mov rdi, rdx\n"
    "    mov rsi, rcx\n"
    "    call __asan_write_lit\n"
    "    lea rax, [rel __asan_msg_frame_hash]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_frame_hash_len\n"
    "    call __asan_write_lit\n"
    "    jmp .frame_num\n"
    ".frame_no_loc:\n"
    "    lea rax, [rel __asan_msg_frame]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_frame_len\n"
    "    call __asan_write_lit\n"
    ".frame_num:\n"
    "    mov rdi, r12\n"
    "    call __asan_write_dec\n"
    "    lea rax, [rel __asan_msg_retaddr]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_retaddr_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-8]\n"
    "    call __asan_write_hex\n"
    "    lea rax, [rel __asan_msg_nl]\n"
    "    mov rdi, rax\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rax, [rbx]\n"
    "    cmp rax, rbx\n"
    "    jle .done\n"
    "    mov rbx, rax\n"
    "    inc r12\n"
    "    jmp .loop\n"
    ".done:\n"
    "    pop r12\n"
    "    pop rbx\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_report:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 56\n"
    "\n"
    "    push rbx\n"
    "    push r14\n"
    "    push r15\n"
    "    mov rbx, rdi\n"
    "    mov r14, rsi\n"
    "    mov rdi, rdx\n"
    "    call __asan_lookup_line\n"
    "    test rax, rax\n"
    "    jz .no_crash_loc\n"
    "    mov [rbp-8], rdx\n"
    "    mov [rbp-16], rcx\n"
    "    mov [rbp-24], r8\n"
    "    mov [rbp-32], r9\n"
    "    mov [rbp-40], r10\n"
    "    mov qword [rbp-48], 1\n"
    "    jmp .have_crash_loc\n"
    ".no_crash_loc:\n"
    "    mov qword [rbp-48], 0\n"
    ".have_crash_loc:\n"
    "    mov rdi, rbx\n"
    "    call __asan_find_record\n"
    "    cmp rax, 0\n"
    "    jl .not_tracked\n"
    "    imul rax, rax, 104\n"
    "    lea r15, [rel __asan_records]\n"
    "    add r15, rax\n"
    "    mov rdi, [r15+56]\n"
    "    mov rsi, [r15+64]\n"
    "    mov rdx, [r15+32]\n"
    "    mov rcx, [r15+40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    cmp qword [r15+48], 0\n"
    "    jne .overflow_msg\n"
    "    lea rdi, [rel __asan_msg_uaf_segv]\n"
    "    mov rsi, __asan_msg_uaf_segv_len\n"
    "    call __asan_write_lit\n"
    "    jmp .print_addr\n"
    ".overflow_msg:\n"
    "    lea rdi, [rel __asan_msg_overflow]\n"
    "    mov rsi, __asan_msg_overflow_len\n"
    "    call __asan_write_lit\n"
    ".print_addr:\n"
    "    mov rdi, rbx\n"
    "    call __asan_write_hex\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    cmp qword [r15+48], 0\n"
    "    jne .print_trace\n"
    "    mov rdi, [r15+56]\n"
    "    mov rsi, [r15+64]\n"
    "    mov rdx, [r15+32]\n"
    "    mov rcx, [r15+40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_note]\n"
    "    mov rsi, __asan_msg_note_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_allocated_here]\n"
    "    mov rsi, __asan_msg_allocated_here_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [r15+88]\n"
    "    mov rsi, [r15+96]\n"
    "    mov rdx, [r15+72]\n"
    "    mov rcx, [r15+80]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_note]\n"
    "    mov rsi, __asan_msg_note_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_freed_here]\n"
    "    mov rsi, __asan_msg_freed_here_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    jmp .print_trace\n"
    ".not_tracked:\n"
    "    cmp qword [rbp-48], 0\n"
    "    je .segv_no_loc\n"
    "    mov rdi, [rbp-8]\n"
    "    mov rsi, [rbp-16]\n"
    "    mov rdx, [rbp-24]\n"
    "    mov rcx, [rbp-32]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_in]\n"
    "    mov rsi, __asan_msg_in_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-40]\n"
    "    call __asan_fn_name\n"
    "    mov rdi, rdx\n"
    "    mov rsi, rcx\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_colon_space]\n"
    "    mov rsi, 2\n"
    "    call __asan_write_lit\n"
    ".segv_no_loc:\n"
    "    lea rdi, [rel __asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_segv]\n"
    "    mov rsi, __asan_msg_segv_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_faddr]\n"
    "    mov rsi, __asan_msg_faddr_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, rbx\n"
    "    call __asan_write_hex\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    cmp rbx, 65536\n"
    "    jge .not_null\n"
    "    lea rdi, [rel __asan_msg_nullderef]\n"
    "    mov rsi, __asan_msg_nullderef_len\n"
    "    call __asan_write_lit\n"
    "    jmp .print_trace\n"
    ".not_null:\n"
    "    lea rdi, [rel __asan_msg_untracked]\n"
    "    mov rsi, __asan_msg_untracked_len\n"
    "    call __asan_write_lit\n"
    ".print_trace:\n"
    "    mov rdi, r14\n"
    "    call __asan_print_trace\n"
    "    mov rdi, 1\n"
    "    call __asan_raw_exit\n"
    "\n"
    "__asan_signal_handler:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov r9, [rsi+16]\n"
    "    mov r10, [rdx+120]\n"
    "    mov r11, [rdx+168]\n"
    "    mov rdi, r9\n"
    "    mov rsi, r10\n"
    "    mov rdx, r11\n"
    "    call __asan_report\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_sigreturn_trampoline:\n"
    "    mov rax, 15\n"
    "    syscall\n"
    "\n"
    "__asan_install_handler:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    lea rax, [rel __asan_signal_handler]\n"
    "    lea r9, [rel __asan_sigact_buf]\n"
    "    mov [r9], rax\n"
    "    mov qword [r9+8], 0x04000004\n"
    "    lea rax, [rel __asan_sigreturn_trampoline]\n"
    "    mov [r9+16], rax\n"
    "    mov qword [r9+24], 0\n"
    "    mov rax, 13\n"
    "    mov rdi, 11\n"
    "    mov rsi, r9\n"
    "    xor rdx, rdx\n"
    "    mov r10, 8\n"
    "    syscall\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_init:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    cmp byte [rel __asan_initialized], 0\n"
    "    jne .done\n"
    "    mov byte [rel __asan_initialized], 1\n"
    "    call __asan_install_handler\n"
    ".done:\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_alloc:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 48\n"
    "\n"
    "    mov [rbp-8], rdi\n"
    "    mov [rbp-16], rsi\n"
    "    mov [rbp-24], rdx\n"
    "    mov [rbp-32], rcx\n"
    "    mov [rbp-40], r8\n"
    "    call __asan_init\n"
    "    mov rax, [rbp-8]\n"
    "    add rax, 4095\n"
    "    and rax, ~4095\n"
    "    mov [rbp-48], rax\n"
    "    mov rdi, rax\n"
    "    add rdi, 8192\n"
    "    mov rsi, 3\n"
    "    call __asan_raw_mmap\n"
    "    cmp rax, -1\n"
    "    jne .ok\n"
    "    mov rdx, 1\n"
    "    leave\n"
    "    ret\n"
    ".ok:\n"
    "    mov r10, rax\n"
    "\n"
    "    mov rdi, r10\n"
    "    mov rsi, 4096\n"
    "    mov rdx, 0\n"
    "    call __asan_raw_mprotect\n"
    "    mov rdi, r10\n"
    "    add rdi, 4096\n"
    "    add rdi, [rbp-48]\n"
    "    mov rsi, 4096\n"
    "    mov rdx, 0\n"
    "    call __asan_raw_mprotect\n"
    "    mov rdx, r10\n"
    "    add rdx, 4096\n"
    "    add rdx, [rbp-48]\n"
    "    sub rdx, [rbp-8]\n"
    "\n"
    "    mov r8, [rel __asan_record_count]\n"
    "    cmp r8, 65536\n"
    "    jge .no_record\n"
    "    mov rax, r8\n"
    "    imul rax, 104\n"
    "    lea r11, [rel __asan_records]\n"
    "    add r11, rax\n"
    "    mov [r11], rdx\n"
    "    mov rax, [rbp-8]\n"
    "    mov [r11+8], rax\n"
    "    mov rax, [rbp-48]\n"
    "    add rax, 8192\n"
    "    mov [r11+16], rax\n"
    "    mov [r11+24], r10\n"
    "    mov rax, [rbp-32]\n"
    "    mov [r11+32], rax\n"
    "    mov rax, [rbp-40]\n"
    "    mov [r11+40], rax\n"
    "    mov qword [r11+48], 1\n"
    "    mov rax, [rbp-16]\n"
    "    mov [r11+56], rax\n"
    "    mov rax, [rbp-24]\n"
    "    mov [r11+64], rax\n"
    "    mov qword [r11+72], 0\n"
    "    mov qword [r11+80], 0\n"
    "    mov qword [r11+88], 0\n"
    "    mov qword [r11+96], 0\n"
    "    inc r8\n"
    "    mov [rel __asan_record_count], r8\n"
    ".no_record:\n"
    "    mov rax, rdx\n"
    "    xor rdx, rdx\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_free:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 48\n"
    "    mov [rbp-8], rdi\n"
    "    mov [rbp-16], rsi\n"
    "    mov [rbp-24], rdx\n"
    "    mov [rbp-32], rcx\n"
    "    mov [rbp-40], r8\n"
    "    call __asan_init\n"
    "    mov rdi, [rbp-8]\n"
    "    call __asan_find_record_by_ptr\n"
    "    cmp rax, 0\n"
    "    jl .invalid_free\n"
    "    imul rcx, rax, 104\n"
    "    lea r8, [rel __asan_records]\n"
    "    add r8, rcx\n"
    "    mov [rbp-48], r8\n"
    "    cmp qword [r8+48], 0\n"
    "    je .double_free\n"
    "    mov qword [r8+48], 0\n"
    "    mov rax, [rbp-32]\n"
    "    mov [r8+72], rax\n"
    "    mov rax, [rbp-40]\n"
    "    mov [r8+80], rax\n"
    "    mov rax, [rbp-16]\n"
    "    mov [r8+88], rax\n"
    "    mov rax, [rbp-24]\n"
    "    mov [r8+96], rax\n"
    "    mov rdi, [r8+24]\n"
    "    mov rsi, [r8+16]\n"
    "    mov rdx, 0\n"
    "    call __asan_raw_mprotect\n"
    "    leave\n"
    "    ret\n"
    ".invalid_free:\n"
    "    mov rdi, [rbp-16]\n"
    "    mov rsi, [rbp-24]\n"
    "    mov rdx, [rbp-32]\n"
    "    mov rcx, [rbp-40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_invalid_free2]\n"
    "    mov rsi, __asan_msg_invalid_free2_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, 1\n"
    "    call __asan_raw_exit\n"
    ".double_free:\n"
    "    mov r8, [rbp-48]\n"
    "\n"
    "    mov rdi, [rbp-16]\n"
    "    mov rsi, [rbp-24]\n"
    "    mov rdx, [rbp-32]\n"
    "    mov rcx, [rbp-40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_double_free2]\n"
    "    mov rsi, __asan_msg_double_free2_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov r8, [rbp-48]\n"
    "    mov rdi, [r8+56]\n"
    "    mov rsi, [r8+64]\n"
    "    mov rdx, [r8+32]\n"
    "    mov rcx, [r8+40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_note]\n"
    "    mov rsi, __asan_msg_note_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_orig_alloc]\n"
    "    mov rsi, __asan_msg_orig_alloc_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov r8, [rbp-48]\n"
    "    mov rdi, [r8+88]\n"
    "    mov rsi, [r8+96]\n"
    "    mov rdx, [r8+72]\n"
    "    mov rcx, [r8+80]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_note]\n"
    "    mov rsi, __asan_msg_note_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_prev_freed]\n"
    "    mov rsi, __asan_msg_prev_freed_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, 1\n"
    "    call __asan_raw_exit\n"
    "\n"
    "__asan_report_leaks:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    push rbx\n"
    "    push r12\n"
    "    push r13\n"
    "    xor rbx, rbx\n"
    "    xor r12, r12\n"
    ".loop:\n"
    "    mov rax, [rel __asan_record_count]\n"
    "    cmp r12, rax\n"
    "    jge .done\n"
    "    imul rax, r12, 104\n"
    "    lea r13, [rel __asan_records]\n"
    "    add r13, rax\n"
    "\n"
    "    cmp qword [r13+48], 0\n"
    "    je .next\n"
    "    inc rbx\n"
    "    mov rdi, [r13+56]\n"
    "    mov rsi, [r13+64]\n"
    "    mov rdx, [r13+32]\n"
    "    mov rcx, [r13+40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [rel __asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_leak]\n"
    "    mov rsi, __asan_msg_leak_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [r13+8]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [rel __asan_msg_bytes_never]\n"
    "    mov rsi, __asan_msg_bytes_never_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [rel __asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    ".next:\n"
    "    inc r12\n"
    "    jmp .loop\n"
    ".done:\n"
    "    pop r13\n"
    "    pop r12\n"
    "    pop rbx\n"
    "    leave\n"
    "    ret\n"
    "\n"    ;

static const char *ST_asan_runtime_asm_src_fasm =
    "\n"
    "section '.bss' writeable\n"
    "align 8\n"
    "__asan_records:      rb 65536 * 104\n"
    "\n"
    "__asan_record_count: rq 1\n"
    "__asan_initialized:  rb 1\n"
    "__asan_sigact_buf:   rb 32\n"
    "__asan_hexbuf:       rb 18\n"
    "__asan_decbuf:       rb 20\n"
    "\n"
    "section '.rodata'\n"
    "__asan_msg_colon: db \":\"\n"
    "__asan_msg_colon_space: db \": \"\n"
    "__asan_msg_err: db \"error: \"\n"
    "__asan_msg_err_len = 7\n"
    "__asan_msg_note: db \"note: \"\n"
    "__asan_msg_note_len = 6\n"
    "__asan_msg_overflow: db \"ASAN: heap-buffer-overflow, faulting address \"\n"
    "__asan_msg_overflow_len = 45\n"
    "__asan_msg_uaf_segv: db \"ASAN: use-after-free, faulting address \"\n"
    "__asan_msg_uaf_segv_len = 39\n"
    "__asan_msg_allocated_here: db \"allocated here\"\n"
    "__asan_msg_allocated_here_len = 14\n"
    "__asan_msg_freed_here: db \"freed here\"\n"
    "__asan_msg_freed_here_len = 10\n"
    "__asan_msg_leak: db \"ASAN: memory leak, \"\n"
    "__asan_msg_leak_len = 19\n"
    "__asan_msg_bytes_never: db \" bytes never freed\"\n"
    "__asan_msg_bytes_never_len = 18\n"
    "__asan_msg_double_free2: db \"ASAN: double free\"\n"
    "__asan_msg_double_free2_len = 17\n"
    "__asan_msg_orig_alloc: db \"originally allocated here\"\n"
    "__asan_msg_orig_alloc_len = 25\n"
    "__asan_msg_prev_freed: db \"previously freed here\"\n"
    "__asan_msg_prev_freed_len = 21\n"
    "__asan_msg_invalid_free2: db \"ASAN: invalid free -- pointer was never returned by heap_alloc\"\n"
    "__asan_msg_invalid_free2_len = 62\n"
    "\n"
    "__asan_msg_sep:         db \"==================================================\", 10\n"
    "__asan_msg_sep_len = 51\n"
    "__asan_msg_segv:        db \"ASAN: SEGV\", 10\n"
    "__asan_msg_segv_len = 11\n"
    "__asan_msg_faddr:       db \"    faulting address: \"\n"
    "__asan_msg_faddr_len = 22\n"
    "__asan_msg_belongs:     db \"    belongs to a \"\n"
    "__asan_msg_belongs_len = 17\n"
    "__asan_msg_bytes_alloc: db \"-byte heap allocation, allocated at line \"\n"
    "__asan_msg_bytes_alloc_len = 41\n"
    "__asan_msg_col:         db \", col \"\n"
    "__asan_msg_col_len = 6\n"
    "__asan_msg_nl:          db 10\n"
    "__asan_msg_uaf:         db \"    this allocation was already freed (use-after-free)\", 10\n"
    "__asan_msg_uaf_len = 55\n"
    "__asan_msg_nullderef:   db \"    null (or near-null) pointer dereference\", 10\n"
    "__asan_msg_nullderef_len = 44\n"
    "__asan_msg_untracked:   db \"    address does not belong to any tracked allocation\", 10\n"
    "__asan_msg_untracked_len = 54\n"
    "__asan_msg_trace:       db \"    stack trace (frame pointers):\", 10\n"
    "__asan_msg_trace_len = 34\n"
    "__asan_msg_frame:       db \"      #\"\n"
    "__asan_msg_frame_len = 7\n"
    "__asan_msg_in:          db \"in \"\n"
    "__asan_msg_in_len = 3\n"
    "__asan_msg_frame_hash: db \" frame #\"\n"
    "__st_msg_oob:          db \"index out of bounds: index \"\n"
    "__st_msg_oob_len = 27\n"
    "__st_msg_oob_of:       db \", length \"\n"
    "__st_msg_oob_of_len = 9\n"
    "__asan_msg_frame_hash_len = 8\n"
    "__asan_msg_retaddr:     db \" return address \"\n"
    "__asan_msg_retaddr_len = 16\n"
    "__asan_msg_invalid_free: db \"ASAN: invalid free -- pointer was never returned by heap_alloc\", 10\n"
    "__asan_msg_invalid_free_len = 63\n"
    "__asan_msg_at_line:     db \"    at line \"\n"
    "__asan_msg_at_line_len = 12\n"
    "__asan_msg_double_free: db \"ASAN: double free\", 10, \"    originally allocated at line \"\n"
    "__asan_msg_double_free_len = 51\n"
    "__asan_msg_this_free:   db \"    this free is at line \"\n"
    "__asan_msg_this_free_len = 25\n"
    "__asan_msg_leak_header: db \"ASAN: memory leak(s) detected\", 10\n"
    "__asan_msg_leak_header_len = 30\n"
    "__asan_msg_leaked:      db \"    leaked \"\n"
    "__asan_msg_leaked_len = 11\n"
    "__asan_msg_bytes_line:  db \" bytes, allocated at line \"\n"
    "__asan_msg_bytes_line_len = 26\n"
    "\n"
    "section '.text' executable\n"
    "\n"
    "__asan_raw_mmap:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rdx, rsi\n"
    "    mov rsi, rdi\n"
    "    xor rdi, rdi\n"
    "    mov r10, 34\n"
    "    mov r8, -1\n"
    "    xor r9, r9\n"
    "    mov rax, 9\n"
    "    syscall\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_raw_mprotect:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, 10\n"
    "    syscall\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_raw_write:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, 1\n"
    "    syscall\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_raw_exit:\n"
    "    mov rax, 60\n"
    "    syscall\n"
    "\n"
    "__asan_write_lit:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rdx, rsi\n"
    "    mov rsi, rdi\n"
    "    mov rdi, 2\n"
    "    call __asan_raw_write\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_write_hex:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, rdi\n"
    "    lea r9, [__asan_hexbuf]\n"
    "    mov byte [r9], 0x30\n"
    "    mov byte [r9+1], 0x78\n"
    "    mov r10, 15\n"
    ".loop:\n"
    "    mov rdx, rax\n"
    "    mov rcx, r10\n"
    "    shl rcx, 2\n"
    "    shr rdx, cl\n"
    "    and rdx, 15\n"
    "    cmp rdx, 10\n"
    "    jl .digit\n"
    "    add rdx, 87\n"
    "    jmp .store\n"
    ".digit:\n"
    "    add rdx, 48\n"
    ".store:\n"
    "    mov r8, 15\n"
    "    sub r8, r10\n"
    "\n"
    "    mov [r9 + 2 + r8], dl\n"
    "    dec r10\n"
    "    jns .loop\n"
    "    mov rdi, 2\n"
    "    lea rsi, [__asan_hexbuf]\n"
    "    mov rdx, 18\n"
    "    call __asan_raw_write\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_write_dec:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, rdi\n"
    "    lea r9, [__asan_decbuf]\n"
    "    mov r10, 20\n"
    "    test rax, rax\n"
    "    jnz .conv\n"
    "    dec r10\n"
    "    mov byte [r9 + r10], 0x30\n"
    "    jmp .out\n"
    ".conv:\n"
    ".loop:\n"
    "    xor rdx, rdx\n"
    "    mov r8, 10\n"
    "    div r8\n"
    "    add rdx, 48\n"
    "    dec r10\n"
    "    mov [r9 + r10], dl\n"
    "    test rax, rax\n"
    "    jnz .loop\n"
    ".out:\n"
    "    mov rdi, 2\n"
    "    lea rsi, [__asan_decbuf]\n"
    "    add rsi, r10\n"
    "    mov rdx, 20\n"
    "    sub rdx, r10\n"
    "    call __asan_raw_write\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_write_loc:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 32\n"
    "    mov [rbp-8], rdi\n"
    "    mov [rbp-16], rsi\n"
    "    mov [rbp-24], rdx\n"
    "    mov [rbp-32], rcx\n"
    "    mov rdi, [rbp-8]\n"
    "    mov rsi, [rbp-16]\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_colon]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-24]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [__asan_msg_colon]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-32]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [__asan_msg_colon_space]\n"
    "    mov rsi, 2\n"
    "    call __asan_write_lit\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__st_bounds_fail:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 16\n"
    "    mov [rbp-8], rdi\n"
    "    mov [rbp-16], rsi\n"
    "    mov rdi, rdx\n"
    "    mov rsi, rcx\n"
    "    mov rdx, r8\n"
    "    mov rcx, r9\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__st_msg_oob]\n"
    "    mov rsi, __st_msg_oob_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-8]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [__st_msg_oob_of]\n"
    "    mov rsi, __st_msg_oob_of_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-16]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, 1\n"
    "    call __asan_raw_exit\n"
    "\n"
    "st_string_eq:\n"
    "    mov r8, [rdi]\n"
    "    mov r9d, [rdi+8]\n"
    "    mov r10, [rsi]\n"
    "    mov r11d, [rsi+8]\n"
    "    cmp r9d, r11d\n"
    "    jne .st_string_eq_false\n"
    "    xor rcx, rcx\n"
    ".st_string_eq_loop:\n"
    "    cmp ecx, r9d\n"
    "    jge .st_string_eq_true\n"
    "    movzx eax, byte [r8+rcx]\n"
    "    movzx edx, byte [r10+rcx]\n"
    "    cmp al, dl\n"
    "    jne .st_string_eq_false\n"
    "    inc rcx\n"
    "    jmp .st_string_eq_loop\n"
    ".st_string_eq_true:\n"
    "    mov rax, 1\n"
    "    ret\n"
    ".st_string_eq_false:\n"
    "    xor rax, rax\n"
    "    ret\n"
    "\n"
    "__asan_find_record:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov r9, rdi\n"
    "    xor rcx, rcx\n"
    "    mov rdx, [__asan_record_count]\n"
    ".loop:\n"
    "    cmp rcx, rdx\n"
    "    jge .notfound\n"
    "    mov rax, rcx\n"
    "    imul rax, 104\n"
    "    lea r8, [__asan_records]\n"
    "    add r8, rax\n"
    "    mov r10, [r8]\n"
    "    sub r10, 4096\n"
    "    cmp r9, r10\n"
    "    jl .next\n"
    "    mov r10, [r8]\n"
    "    add r10, [r8+8]\n"
    "    add r10, 4096\n"
    "    cmp r9, r10\n"
    "    jge .next\n"
    "    mov rax, rcx\n"
    "    leave\n"
    "    ret\n"
    ".next:\n"
    "    inc rcx\n"
    "    jmp .loop\n"
    ".notfound:\n"
    "    mov rax, -1\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_find_record_by_ptr:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov r9, rdi\n"
    "    xor rcx, rcx\n"
    "    mov rdx, [__asan_record_count]\n"
    ".loop:\n"
    "    cmp rcx, rdx\n"
    "    jge .notfound\n"
    "    mov rax, rcx\n"
    "    imul rax, 104\n"
    "    lea r8, [__asan_records]\n"
    "    add r8, rax\n"
    "    cmp [r8], r9\n"
    "    je .found\n"
    "    inc rcx\n"
    "    jmp .loop\n"
    ".found:\n"
    "    mov rax, rcx\n"
    "    leave\n"
    "    ret\n"
    ".notfound:\n"
    "    mov rax, -1\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_lookup_line:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 16\n"
    "    mov qword [rbp-8], 0\n"
    "    mov r9, rdi\n"
    "    mov r10, [__asan_dbg_row_count]\n"
    "    lea r11, [__asan_dbg_rows]\n"
    "    xor rcx, rcx\n"
    ".loop:\n"
    "    cmp rcx, r10\n"
    "    jge .done\n"
    "    mov rax, rcx\n"
    "    imul rax, 48\n"
    "    add rax, r11\n"
    "    cmp qword [rax], r9\n"
    "    jg .done\n"
    "\n"
    "    mov [rbp-8], rax\n"
    "    inc rcx\n"
    "    jmp .loop\n"
    ".done:\n"
    "    mov rax, [rbp-8]\n"
    "    test rax, rax\n"
    "    jz .notfound\n"
    "    mov r10, [rax+40]\n"
    "    mov rdx, r10\n"
    "    imul rdx, 24\n"
    "    lea rcx, [__asan_dbg_fn_names]\n"
    "    add rdx, rcx\n"
    "    cmp r9, [rdx+16]\n"
    "    jge .notfound\n"
    "\n"
    "    mov rdx, [rax+8]\n"
    "    mov rcx, [rax+16]\n"
    "    mov r8, [rax+24]\n"
    "    mov r9, [rax+32]\n"
    "    mov rax, 1\n"
    "    leave\n"
    "    ret\n"
    ".notfound:\n"
    "    xor rax, rax\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_fn_name:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov rax, rdi\n"
    "    imul rax, 24\n"
    "    lea r10, [__asan_dbg_fn_names]\n"
    "    add rax, r10\n"
    "    mov rdx, [rax]\n"
    "    mov rcx, [rax+8]\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_print_trace:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 32\n"
    "    push rbx\n"
    "    push r12\n"
    "    mov rbx, rdi\n"
    "\n"
    "    lea rax, [__asan_msg_trace]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_trace_len\n"
    "    call __asan_write_lit\n"
    "    xor r12, r12\n"
    ".loop:\n"
    "    cmp r12, 32\n"
    "    jge .done\n"
    "    test rbx, rbx\n"
    "    jz .done\n"
    "    mov rax, [rbx+8]\n"
    "    test rax, rax\n"
    "    jz .done\n"
    "    mov [rbp-8], rax\n"
    "    mov rdi, rax\n"
    "    call __asan_lookup_line\n"
    "    test rax, rax\n"
    "    jz .frame_no_loc\n"
    "    mov [rbp-16], r10\n"
    "    mov rdi, rdx\n"
    "    mov rsi, rcx\n"
    "    mov rdx, r8\n"
    "    mov rcx, r9\n"
    "    call __asan_write_loc\n"
    "    lea rax, [__asan_msg_in]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_in_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-16]\n"
    "    call __asan_fn_name\n"
    "    mov rdi, rdx\n"
    "    mov rsi, rcx\n"
    "    call __asan_write_lit\n"
    "    lea rax, [__asan_msg_frame_hash]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_frame_hash_len\n"
    "    call __asan_write_lit\n"
    "    jmp .frame_num\n"
    ".frame_no_loc:\n"
    "    lea rax, [__asan_msg_frame]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_frame_len\n"
    "    call __asan_write_lit\n"
    ".frame_num:\n"
    "    mov rdi, r12\n"
    "    call __asan_write_dec\n"
    "    lea rax, [__asan_msg_retaddr]\n"
    "    mov rdi, rax\n"
    "    mov rsi, __asan_msg_retaddr_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-8]\n"
    "    call __asan_write_hex\n"
    "    lea rax, [__asan_msg_nl]\n"
    "    mov rdi, rax\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rax, [rbx]\n"
    "    cmp rax, rbx\n"
    "    jle .done\n"
    "    mov rbx, rax\n"
    "    inc r12\n"
    "    jmp .loop\n"
    ".done:\n"
    "    pop r12\n"
    "    pop rbx\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_report:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 56\n"
    "\n"
    "    push rbx\n"
    "    push r14\n"
    "    push r15\n"
    "    mov rbx, rdi\n"
    "    mov r14, rsi\n"
    "    mov rdi, rdx\n"
    "    call __asan_lookup_line\n"
    "    test rax, rax\n"
    "    jz .no_crash_loc\n"
    "    mov [rbp-8], rdx\n"
    "    mov [rbp-16], rcx\n"
    "    mov [rbp-24], r8\n"
    "    mov [rbp-32], r9\n"
    "    mov [rbp-40], r10\n"
    "    mov qword [rbp-48], 1\n"
    "    jmp .have_crash_loc\n"
    ".no_crash_loc:\n"
    "    mov qword [rbp-48], 0\n"
    ".have_crash_loc:\n"
    "    mov rdi, rbx\n"
    "    call __asan_find_record\n"
    "    cmp rax, 0\n"
    "    jl .not_tracked\n"
    "    imul rax, rax, 104\n"
    "    lea r15, [__asan_records]\n"
    "    add r15, rax\n"
    "    mov rdi, [r15+56]\n"
    "    mov rsi, [r15+64]\n"
    "    mov rdx, [r15+32]\n"
    "    mov rcx, [r15+40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    cmp qword [r15+48], 0\n"
    "    jne .overflow_msg\n"
    "    lea rdi, [__asan_msg_uaf_segv]\n"
    "    mov rsi, __asan_msg_uaf_segv_len\n"
    "    call __asan_write_lit\n"
    "    jmp .print_addr\n"
    ".overflow_msg:\n"
    "    lea rdi, [__asan_msg_overflow]\n"
    "    mov rsi, __asan_msg_overflow_len\n"
    "    call __asan_write_lit\n"
    ".print_addr:\n"
    "    mov rdi, rbx\n"
    "    call __asan_write_hex\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    cmp qword [r15+48], 0\n"
    "    jne .print_trace\n"
    "    mov rdi, [r15+56]\n"
    "    mov rsi, [r15+64]\n"
    "    mov rdx, [r15+32]\n"
    "    mov rcx, [r15+40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_note]\n"
    "    mov rsi, __asan_msg_note_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_allocated_here]\n"
    "    mov rsi, __asan_msg_allocated_here_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [r15+88]\n"
    "    mov rsi, [r15+96]\n"
    "    mov rdx, [r15+72]\n"
    "    mov rcx, [r15+80]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_note]\n"
    "    mov rsi, __asan_msg_note_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_freed_here]\n"
    "    mov rsi, __asan_msg_freed_here_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    jmp .print_trace\n"
    ".not_tracked:\n"
    "    cmp qword [rbp-48], 0\n"
    "    je .segv_no_loc\n"
    "    mov rdi, [rbp-8]\n"
    "    mov rsi, [rbp-16]\n"
    "    mov rdx, [rbp-24]\n"
    "    mov rcx, [rbp-32]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_in]\n"
    "    mov rsi, __asan_msg_in_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [rbp-40]\n"
    "    call __asan_fn_name\n"
    "    mov rdi, rdx\n"
    "    mov rsi, rcx\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_colon_space]\n"
    "    mov rsi, 2\n"
    "    call __asan_write_lit\n"
    ".segv_no_loc:\n"
    "    lea rdi, [__asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_segv]\n"
    "    mov rsi, __asan_msg_segv_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_faddr]\n"
    "    mov rsi, __asan_msg_faddr_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, rbx\n"
    "    call __asan_write_hex\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    cmp rbx, 65536\n"
    "    jge .not_null\n"
    "    lea rdi, [__asan_msg_nullderef]\n"
    "    mov rsi, __asan_msg_nullderef_len\n"
    "    call __asan_write_lit\n"
    "    jmp .print_trace\n"
    ".not_null:\n"
    "    lea rdi, [__asan_msg_untracked]\n"
    "    mov rsi, __asan_msg_untracked_len\n"
    "    call __asan_write_lit\n"
    ".print_trace:\n"
    "    mov rdi, r14\n"
    "    call __asan_print_trace\n"
    "    mov rdi, 1\n"
    "    call __asan_raw_exit\n"
    "\n"
    "__asan_signal_handler:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    mov r9, [rsi+16]\n"
    "    mov r10, [rdx+120]\n"
    "    mov r11, [rdx+168]\n"
    "    mov rdi, r9\n"
    "    mov rsi, r10\n"
    "    mov rdx, r11\n"
    "    call __asan_report\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_sigreturn_trampoline:\n"
    "    mov rax, 15\n"
    "    syscall\n"
    "\n"
    "__asan_install_handler:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    lea rax, [__asan_signal_handler]\n"
    "    lea r9, [__asan_sigact_buf]\n"
    "    mov [r9], rax\n"
    "    mov qword [r9+8], 0x04000004\n"
    "    lea rax, [__asan_sigreturn_trampoline]\n"
    "    mov [r9+16], rax\n"
    "    mov qword [r9+24], 0\n"
    "    mov rax, 13\n"
    "    mov rdi, 11\n"
    "    mov rsi, r9\n"
    "    xor rdx, rdx\n"
    "    mov r10, 8\n"
    "    syscall\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_init:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    cmp byte [__asan_initialized], 0\n"
    "    jne .done\n"
    "    mov byte [__asan_initialized], 1\n"
    "    call __asan_install_handler\n"
    ".done:\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_alloc:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 48\n"
    "\n"
    "    mov [rbp-8], rdi\n"
    "    mov [rbp-16], rsi\n"
    "    mov [rbp-24], rdx\n"
    "    mov [rbp-32], rcx\n"
    "    mov [rbp-40], r8\n"
    "    call __asan_init\n"
    "    mov rax, [rbp-8]\n"
    "    add rax, 4095\n"
    "    and rax, -4096\n"
    "    mov [rbp-48], rax\n"
    "    mov rdi, rax\n"
    "    add rdi, 8192\n"
    "    mov rsi, 3\n"
    "    call __asan_raw_mmap\n"
    "    cmp rax, -1\n"
    "    jne .ok\n"
    "    mov rdx, 1\n"
    "    leave\n"
    "    ret\n"
    ".ok:\n"
    "    mov r10, rax\n"
    "\n"
    "    mov rdi, r10\n"
    "    mov rsi, 4096\n"
    "    mov rdx, 0\n"
    "    call __asan_raw_mprotect\n"
    "    mov rdi, r10\n"
    "    add rdi, 4096\n"
    "    add rdi, [rbp-48]\n"
    "    mov rsi, 4096\n"
    "    mov rdx, 0\n"
    "    call __asan_raw_mprotect\n"
    "    mov rdx, r10\n"
    "    add rdx, 4096\n"
    "    add rdx, [rbp-48]\n"
    "    sub rdx, [rbp-8]\n"
    "\n"
    "    mov r8, [__asan_record_count]\n"
    "    cmp r8, 65536\n"
    "    jge .no_record\n"
    "    mov rax, r8\n"
    "    imul rax, 104\n"
    "    lea r11, [__asan_records]\n"
    "    add r11, rax\n"
    "    mov [r11], rdx\n"
    "    mov rax, [rbp-8]\n"
    "    mov [r11+8], rax\n"
    "    mov rax, [rbp-48]\n"
    "    add rax, 8192\n"
    "    mov [r11+16], rax\n"
    "    mov [r11+24], r10\n"
    "    mov rax, [rbp-32]\n"
    "    mov [r11+32], rax\n"
    "    mov rax, [rbp-40]\n"
    "    mov [r11+40], rax\n"
    "    mov qword [r11+48], 1\n"
    "    mov rax, [rbp-16]\n"
    "    mov [r11+56], rax\n"
    "    mov rax, [rbp-24]\n"
    "    mov [r11+64], rax\n"
    "    mov qword [r11+72], 0\n"
    "    mov qword [r11+80], 0\n"
    "    mov qword [r11+88], 0\n"
    "    mov qword [r11+96], 0\n"
    "    inc r8\n"
    "    mov [__asan_record_count], r8\n"
    ".no_record:\n"
    "    mov rax, rdx\n"
    "    xor rdx, rdx\n"
    "    leave\n"
    "    ret\n"
    "\n"
    "__asan_free:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    sub rsp, 48\n"
    "    mov [rbp-8], rdi\n"
    "    mov [rbp-16], rsi\n"
    "    mov [rbp-24], rdx\n"
    "    mov [rbp-32], rcx\n"
    "    mov [rbp-40], r8\n"
    "    call __asan_init\n"
    "    mov rdi, [rbp-8]\n"
    "    call __asan_find_record_by_ptr\n"
    "    cmp rax, 0\n"
    "    jl .invalid_free\n"
    "    imul rcx, rax, 104\n"
    "    lea r8, [__asan_records]\n"
    "    add r8, rcx\n"
    "    mov [rbp-48], r8\n"
    "    cmp qword [r8+48], 0\n"
    "    je .double_free\n"
    "    mov qword [r8+48], 0\n"
    "    mov rax, [rbp-32]\n"
    "    mov [r8+72], rax\n"
    "    mov rax, [rbp-40]\n"
    "    mov [r8+80], rax\n"
    "    mov rax, [rbp-16]\n"
    "    mov [r8+88], rax\n"
    "    mov rax, [rbp-24]\n"
    "    mov [r8+96], rax\n"
    "    mov rdi, [r8+24]\n"
    "    mov rsi, [r8+16]\n"
    "    mov rdx, 0\n"
    "    call __asan_raw_mprotect\n"
    "    leave\n"
    "    ret\n"
    ".invalid_free:\n"
    "    mov rdi, [rbp-16]\n"
    "    mov rsi, [rbp-24]\n"
    "    mov rdx, [rbp-32]\n"
    "    mov rcx, [rbp-40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_invalid_free2]\n"
    "    mov rsi, __asan_msg_invalid_free2_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, 1\n"
    "    call __asan_raw_exit\n"
    ".double_free:\n"
    "    mov r8, [rbp-48]\n"
    "\n"
    "    mov rdi, [rbp-16]\n"
    "    mov rsi, [rbp-24]\n"
    "    mov rdx, [rbp-32]\n"
    "    mov rcx, [rbp-40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_double_free2]\n"
    "    mov rsi, __asan_msg_double_free2_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov r8, [rbp-48]\n"
    "    mov rdi, [r8+56]\n"
    "    mov rsi, [r8+64]\n"
    "    mov rdx, [r8+32]\n"
    "    mov rcx, [r8+40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_note]\n"
    "    mov rsi, __asan_msg_note_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_orig_alloc]\n"
    "    mov rsi, __asan_msg_orig_alloc_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov r8, [rbp-48]\n"
    "    mov rdi, [r8+88]\n"
    "    mov rsi, [r8+96]\n"
    "    mov rdx, [r8+72]\n"
    "    mov rcx, [r8+80]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_note]\n"
    "    mov rsi, __asan_msg_note_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_prev_freed]\n"
    "    mov rsi, __asan_msg_prev_freed_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    "    mov rdi, 1\n"
    "    call __asan_raw_exit\n"
    "\n"
    "__asan_report_leaks:\n"
    "    push rbp\n"
    "    mov rbp, rsp\n"
    "    push rbx\n"
    "    push r12\n"
    "    push r13\n"
    "    xor rbx, rbx\n"
    "    xor r12, r12\n"
    ".loop:\n"
    "    mov rax, [__asan_record_count]\n"
    "    cmp r12, rax\n"
    "    jge .done\n"
    "    imul rax, r12, 104\n"
    "    lea r13, [__asan_records]\n"
    "    add r13, rax\n"
    "\n"
    "    cmp qword [r13+48], 0\n"
    "    je .next\n"
    "    inc rbx\n"
    "    mov rdi, [r13+56]\n"
    "    mov rsi, [r13+64]\n"
    "    mov rdx, [r13+32]\n"
    "    mov rcx, [r13+40]\n"
    "    call __asan_write_loc\n"
    "    lea rdi, [__asan_msg_err]\n"
    "    mov rsi, __asan_msg_err_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_leak]\n"
    "    mov rsi, __asan_msg_leak_len\n"
    "    call __asan_write_lit\n"
    "    mov rdi, [r13+8]\n"
    "    call __asan_write_dec\n"
    "    lea rdi, [__asan_msg_bytes_never]\n"
    "    mov rsi, __asan_msg_bytes_never_len\n"
    "    call __asan_write_lit\n"
    "    lea rdi, [__asan_msg_nl]\n"
    "    mov rsi, 1\n"
    "    call __asan_write_lit\n"
    ".next:\n"
    "    inc r12\n"
    "    jmp .loop\n"
    ".done:\n"
    "    pop r13\n"
    "    pop r12\n"
    "    pop rbx\n"
    "    leave\n"
    "    ret\n"    ;

void ST_asan_write_runtime_asm(FILE *out, b8 use_fasm) {
    fputs(use_fasm ? ST_asan_runtime_asm_src_fasm : ST_asan_runtime_asm_src, out);
}

b8 ST_asan_instrument(ST_arena_t *arena, ST_program_t *prog, ST_srcmap_t *srcs) {
    ST_forrange(0, prog->decls.count) {
        ST_decl_t *d = prog->decls.items[i];
        if (d && d->kind == ST_DE_FN)
            ST_asan_walk_stmts(arena, &d->fn.body, d->file);
    }

    ST_string_t decls_file = ST_cstr_to_str((char *)"<asan-extern-decls>");
    ST_string_t decls_src = ST_cstr_to_str((char *)ST_asan_extern_decls_src);
    ST_srcmap_put(srcs, decls_file, decls_src);

    ST_tokens_t decls_toks = ST_lex(arena, decls_src, decls_file);
    ST_program_t decls_prog = {0};
    if (!ST_parse(arena, decls_toks, decls_src, decls_file, srcs, &decls_prog)) {
        fprintf(stderr, "storthc: internal: the built-in ASan extern declarations failed to "
                        "parse -- this is a compiler bug, not a problem with your program\n");
        return 0;
    }

    ST_forrange(0, decls_prog.decls.count)
        ST_da_append_arena(arena, &prog->decls, decls_prog.decls.items[i]);

    ST_decl_t *main_decl = NULL;
    ST_forrange(0, prog->decls.count) {
        ST_decl_t *d = prog->decls.items[i];
        if (d && d->kind == ST_DE_FN && ST_string_eq_cstr(d->name, "main")) {
            main_decl = d;
            break;
        }
    }
    if (!main_decl)
        return 1;

    ST_expr_t *init_callee = ST_expr_new(arena, ST_EX_IDENT, main_decl->line, main_decl->col);
    init_callee->name = ST_cstr_to_str((char *)"__asan_init");
    ST_expr_t *init_call = ST_expr_new(arena, ST_EX_CALL, main_decl->line, main_decl->col);
    init_call->call.callee = init_callee;
    ST_stmt_t *init_stmt = ST_stmt_new(arena, ST_ST_EXPR, main_decl->line, main_decl->col);
    init_stmt->expr = init_call;

    ST_expr_t *report_call = ST_asan_report_leaks_call(arena, main_decl->line, main_decl->col);
    ST_stmt_t *report_stmt = ST_stmt_new(arena, ST_ST_EXPR, main_decl->line, main_decl->col);
    report_stmt->expr = report_call;

    ST_stmt_t *defer_stmt = ST_stmt_new(arena, ST_ST_DEFER, main_decl->line, main_decl->col);
    defer_stmt->defer_stmt = report_stmt;

    ST_stmts_t new_body = {0};
    ST_da_append_arena(arena, &new_body, init_stmt);
    ST_da_append_arena(arena, &new_body, defer_stmt);
    ST_forrange(0, main_decl->fn.body.count) ST_da_append_arena(arena, &new_body, main_decl->fn.body.items[i]);
    main_decl->fn.body = new_body;

    return 1;
}
